name: opencity3d
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib
  - pip:
    - pyrender==0.1.45
    - scipy==1.13
    - trimesh==4.5.2
    - tqdm
    - numpy<2
